### ISSUE TITLE
Event listeners are not removed on destroy

### ISSUE THREAD

**Issue by sineed** [gaslight/phoenix-custom-event-hook#2]
Currently all event listeners stay on a page after the child component of a LiveView has been destroyed. The problem with this is if I need to destroy one instance of component A and then mount the second instance of the same component A and then fire an event defined in `phx-custom-event-...` then I get two events on a server: one for the new instance of component A and the second one for the LiveView because the old component instance is no longer exists. The last message generates expected error on a server because LiveView doesn't have handlers defined in components.

The problem can be easily fixed by removing listeners in the `destroyed` function.

I can share the code after I will be sure it works in my project if you want to.

**Comment by superchris** [comment]
Sorry for ridiculously late response, I haven't needed to touch the code in the repo for awhile. I'm getting back to it now and will likely cut a new version soon, so if you have this code to share I'd love to get it in. If not I can look into this myself but it seems a bit tricky to make sure I can reproduce this issue.

**Comment by superchris** [comment]
Fixed and covered by test
